---
# tasks file for prod
- name: update package
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Ensure Tomcat  package is present
  apt:
    name: tomcat9
    state: present

- name: Start service Tomcat
  service:
    name: tomcat9
    state: started

- name: Ensure package rsync
  apt: 
    name: rsync
    state: present

- name: copy war app 
  synchronize:
    src: /home/ubuntu/app/target/hello-1.0.war
    dest: /var/lib/tomcat9/webapps
  delegate_to: 18.232.145.53
